#!/bin/sh -eu
#
# Keeps call transfer on when nobody is in.

. "`dirname "$0"`/tel.conf"

journalctl -fu visitors -o cat -n 0 | jq --unbuffered -r 'if .occupied==.ts then "in" else if .ids==[] then "out" else empty end end | @text' | while read -r state; do
    case $state in
	out)
	    # Activate call transfer
	    chat -vsT "$TEL" ABORT ERROR ABORT 'NO CARRIER' '' 'AT+CCFC=0,1,"\T",145,1' OK <"$DEV" >"$DEV"
	    ;;
	in)
	    # Cancel call transfer
	    chat -vs ABORT ERROR ABORT 'NO CARRIER' '' 'AT+CCFC=0,0' OK <"$DEV" >"$DEV"
	    ;;
    esac
done
