#!/usr/bin/env php
<?php
require_once(__DIR__.'/common.php');
require_once(__DIR__.'/lib/visitors.php');
require_once(__DIR__.'/lib/irc.php');

// Search current visitors
$req = [
    'lease' => $dhcp_lease_secs,
    'now' => gettimeofday(true)
];
$visits = get_visitors($req);

if (count($visits) === 0) {
    $msg = "Kerhoilta alkaisi, mutta Hacklab on vielä tyhjä :/";
} else {
    $msg = "Kerhoilta alkoi, paikalla ";
    $msg .= count($visits) > 1 ? 'ovat ' : 'on ';
    foreach ($visits as $user) {
        $msg .=
            $user['nick'].' (saapui '.
            date('H:i', $user['enter']).
            '), ';
    }
    $msg = substr($msg, 0, -2); // Remove comma+space
    $msg .= ". Tervetuloa!";
}

to_irc($msg);
