#!/bin/bash -eu
#
# This contains bashisms like read -t

cd "`dirname $0`"

journalctl -fu visitors -o cat -n 1 _TRANSPORT=stdout |
    jq --unbuffered -r 'if .ids==[] then empty else "in" end | @text' | {
    while ! read -t 15 MSG; do
	echo "Hei, kuka sinä olet? Laita veelan päälle ja rekisteröidy tarvittaessa nettisivuillamme."
    done
    # Someone in
    echo "Tervetuloa häkläbille, `./who`"
    sleep 5
    kill `ps -o pid --no-headers --ppid $$`
} | espeak-ng -v fi -p 60
