#!/usr/bin/env php
<?php
require_once(__DIR__.'/lib/common.php');
require_once(__DIR__.'/lib/visitors.php');

// Exit code is 0 if lab is empty, 1 otherwise

$visits = get_visitors([
    'lease' => $dhcp_lease_secs,
    'now' => gettimeofday(true)
]);


if (empty($visits)) {
    exit(1);
}

print($visits[0]['nick']."\n");

