#!/usr/bin/env php
<?php
# Data cleaner. See README.md for instructions.

require_once(__DIR__.'/../common.php');
$dhcp_lease_secs = 600; // 10 mins because old data is more dirty

// Database
$select_old_visit = $db->prepare("
    SELECT mac, enter, leave, ip, hostname
    FROM visit
    ORDER BY enter
");
$add_visit = $db->prepare("
    INSERT INTO visit_new (mac, enter, leave, ip, hostname)
    VALUES (:mac,:enter,:leave,:ip,:hostname)
");
$update_visit = $db->prepare("
    UPDATE visit_new
    SET leave=:leave
    WHERE leave>:leave-:lease AND mac=:mac
");
$update_visit->bindValue('lease',$dhcp_lease_secs);

$db->exec('BEGIN');
$visits = db_execute($select_old_visit);

while (($data = $visits->fetchArray(SQLITE3_ASSOC))) {
    // Try to update visit first if possible, otherwise insert new.
    db_execute($update_visit, $data);
    if ($db->changes() === 0) {
        db_execute($add_visit, $data);
    }
}

$db->exec('END');
