#!/usr/bin/env php
<?php
# Import old data in column format. Import old data to empty table only!

require_once(__DIR__.'/../common.php');

// Database
$add_visit = $db->prepare("
    INSERT INTO visit (mac, enter, leave, ip, hostname)
    VALUES (:mac,:now,:now,'','')
");
$update_visit = $db->prepare("
    UPDATE visit
    SET leave=:now
    WHERE leave>:now-:lease AND mac=:mac
");
$update_visit->bindValue('lease',$merge_window_sec);

$db->exec('BEGIN');

while (($line = stream_get_line(STDIN, 2048, "\n"))) {
    $macs = explode(' ', $line);
    $time = DateTime::createFromFormat('Y-m-d\TH-i-s' , array_shift($macs))->getTimestamp();
    foreach($macs as $mac) {
        $data = [
            'now' => $time,
            'mac' => strtoupper(str_replace(':', '', $mac)),
        ];

        // Try to update visit first if possible, otherwise insert new.
        db_execute($update_visit, $data);
        if ($db->changes() === 0) {
            db_execute($add_visit, $data);
        }
    }
}

$db->exec('END');
