#!/bin/sh -eu
#
# Dump SQL database, merge overlapping visits and push it to the
# public git repository.

db="${2:-`dirname "$0"`/../db/db.sqlite}"
cd "$1"

sqlite3 "$db" -csv -header "select distinct u.id as id,u.nick as nick from public_visit p join user u using (id) order by id" >user.csv

sqlite3 "$db" -csv "select id,enter,leave+75 from public_visit order by id,enter" | {
    # Header
    echo id,enter,leave
    
    # Read first line
    IFS=, read old_id old_enter old_leave foo

    # Process remaining lines
    while IFS=, read id enter leave foo; do
	if test $id != $old_id -o $enter -gt $old_leave; then
	    echo $old_id,$old_enter,$old_leave
	    
	    # Store old values
	    old_id=$id
	    old_enter=$enter
	    old_leave=$leave
	else
	    test $leave -gt $old_leave && old_leave=$leave
	fi
    done

    # Print last line
    echo $old_id,$old_enter,$old_leave
} | sort -n -t , -k 2 -o visit.csv

git add .
git commit -m "Daily visitor database dump" --allow-empty
git push
